### ISSUE TITLE
Error when opening application.

### ISSUE THREAD

**Issue by Micaxs** [OliveOil1/FLauncher#2]
I run the application (v0.9.2-alpha), either as normal user or as administrator and I receive an error.

`Header with name 'parameters' was not found. If youa re expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.`

I assume something goes wrong here? I'm sadly on Windows 10 and was hoping for a simple quick app launcher. But this seems to not really work as of yet. The app loads but I can't really do much within the options. I assume this related to this error message?

**Comment by oliveoil1** [comment]
Hi, I have looked into your issue and found the cause.
Turns out the program wasn't creating the data files correctly, I have fixed it in 0.9.3-alpha.

For a quick fix, could you try the steps below?
1. Make sure FLauncher is open
2. Right click the tray icon (the blue square with the arrow)
3. Click `Open Data Location`
4. Open `Aliases.csv`
5. Quit Flauncher (right click tray icon > quit)
6. Replace the contents of `Aliases.csv` with: `alias,full_path,parameters`
7. Save file
8. Open FLauncher and it should work

**Comment by oliveoil1** [comment]
Issue solved
